# Generated by Django 5.0.6 on 2024-06-20 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=18)),
                ('date_of_birth', models.DateField()),
                ('education_level', models.CharField(max_length=20)),
                ('subject_specialisation', models.CharField(max_length=30)),
                ('phone_number', models.CharField(max_length=20)),
                ('courses_taught', models.TextField()),
            ],
        ),
    ]
